brew "bat"      # A cat(1) clone with sytax highlighting
brew "eza"      # A modern replacement for 'ls'
brew "fzf"      # A command-line fuzzy finder
brew "lnav"	# A log navigator
brew "nvm"	# A node version manager
brew "ripgrep"  # A faster grep command
brew "zoxide"   # A smarter cd command
