brew "bat"      # A cat(1) clone with sytax highlighting
brew "eza"      # A modern replacement for 'ls'
brew "fd"       # A modern replacement for 'find'
brew "figlet"	# Banner-like program prints strings as ASCII art
brew "fzf"      # A command-line fuzzy finder
brew "lnav"	# A log navigator
brew "nvm"	# A node version manager
brew "ripgrep"  # A faster grep command
brew "starship" # A customizable prompt
brew "vivid"    # Generator for LS_COLORS with support for multiple color themes
brew "zoxide"   # A smarter cd command
brew "zsh-autosuggestions" # Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-syntax-highlighting" # A syntax highlighter

