#!/bin/zsh

function chrome() {
    if [[ -n "$WSL_DISTRO_NAME" ]]; then
      # WSL: Use a subshell to temporarily change the CWD and avoid the UNC path warning
      (
        cd /mnt/c/ || return 1
        cmd.exe /C "start chrome.exe $*"
      )
    else
      # macOS: Use the open command
      open -a "Google Chrome" "$@"
    fi
}

function tm() {
    if [[ -n "$WSL_DISTRO_NAME" ]]; then
      # WSL: Use cmd.exe to launch the Windows executable
      (
        cd /mnt/c/ || return 1
        cmd.exe /C "start taskmgr.exe"
      )
    else
      # macOS: Provide an alternative or handle an error
      echo "Task Manager is a Windows-specific application."
    fi
}

function cd() {
  if [[ -z "$1" ]]; then
    local dir
    dir=$( (printf "~\n"; zoxide query -l) | sort -u | fzf)

    if [[ -n "$dir" ]]; then
      builtin cd "$dir"
    fi
  else
    builtin cd "$@"
  fi
}

function v() {
  local file
  file=$(fd --type f | fzf --preview "bat --color=always --line-range :500 {}" --bind "shift-up:preview-page-up,shift-down:preview-page-down")

  if [[ -n "$file" ]]; then
    vim "$file"
  fi
}

function gl() {
  git log --oneline --graph --all --color=always | \
    fzf --no-sort --reverse --ansi \
    --bind 'shift-up:preview-page-up,shift-down:preview-page-down' \
    --preview "git --no-pager show --color=always \$(echo {} | sed 's/^[^a-f0-9]*//' | cut -d' ' -f1)"
}
